name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u chunglnt0609 -p 6Linh@24012000
      - name: Build docker image
        run: docker build --no-cache -t chunglnt0609/demo .
      - name: Publish image to docker hub
        run: docker push chunglnt0609/demo:latest

  deploy:
    needs: build
    runs-on: [demo]
    steps:
      - name: Start docker
        run: sudo service docker start
      - name: Pull Image from docker hub
        run: docker pull chunglnt0609/demo:latest
      - name: Delete old container
        run: docker rm -f demo
      - name: Run docker container
        run: docker run -d -p 8081:8081 --name demo chunglnt0609/demo
